apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-w2
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-local-worker-2